POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstName":"Loo",
    "lastName":"Le",
    "email":"h@m.com",
    "passwHash": "123",
    "birthday":"2001-12-01",
    "gender":"male"
}


###
GET  http://localhost:5000/api/users?page=1&results=2  

### 200

GET  http://localhost:5000/api/users/24 


### 404
GET  http://localhost:5000/api/users/30

 