POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstName":"Jane",
    "lastName":"Doe",
    "email":"m6@m.com",
    "passwHash": "123",
    "birthday":"2001-12-01",
    "gender":"male"
}