POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstName":"Loo",
    "lastName":"Le",
    "email":"h1@m.com",
    "passwHash": "123",
    "birthday":"2001-12-01",
    "gender":"male"
}


###
GET  http://localhost:5000/api/users?page=1&results=2  

### 200

GET  http://localhost:5000/api/users/24 


### 404
GET  http://localhost:5000/api/users/30  


### 200

DELETE http://localhost:5000/api/users/24 


### 404
DELETE http://localhost:5000/api/users/1231


### 200
PATCH http://localhost:5000/api/users/9
Content-Type: application/json

{
    "lastName":"Le"
}

### 404
PATCH http://localhost:5000/api/users/98
Content-Type: application/json

{
    "lastName":"Le"
}

### 500 (422)
PATCH http://localhost:5000/api/users/9
Content-Type: application/json

{
    "firstName":"123154542132"
}

